### ISSUE TITLE
Incorrect information displayed for iOS Safari (iPhone 15 Pro)

### ISSUE THREAD

**Issue by sunstarjeff** [philfung/add-to-homescreen#23] opened 2024-08-07 19:29 UTC
Hello.  I am trying to use this application, but when I test on my phone (iPhone 15 Pro) using the regular Safari browser, it is displaying an incorrect message:

"Tap the button below to open your system browser".

Screen shot:

![screenshot](https://github.com/user-attachments/assets/c5ef99f1-5346-4c01-8c6a-a891c6d9a13a)

Is there an update needed for newer browsers?

**Comment by philfung** [comment] 2024-08-07 19:56
that looks like a bug, will fix.  
what IOS version are you on?

**Comment by philfung** [comment] 2024-08-07 19:58
hello, it doesn't look like you're using Safari app directly.  Do you know if you opened this link from within another app, like Instagram, Github app , Google search app, etc?

**Comment by sunstarjeff** [comment] 2024-08-07 20:02
No, its definitely the native Safari browser on the iPhone.  I tapped on the Safari icon and loaded the link.  You can see in my screenshot this icon is present at the bottom center of the browser.

![image](https://github.com/user-attachments/assets/6a82de10-8223-4583-8d8f-2b175dea2f72)

**Comment by philfung** [comment] 2024-08-08 03:02
thank you, i can't seem to reproduce on IOS 17.5 Simulator (and there's no IOS 17.6 Simulator available yet for download yet).
Once 17.6 Simulator is available, I'll be able to debug.

<img width="407" alt="Screenshot 2024-08-07 at 7 57 59 PM" src="https://github.com/user-attachments/assets/5c236081-6624-4fb0-afac-67b54ee28ff6">

**Comment by sunstarjeff** [comment] 2024-08-08 15:12
Thank you.  I tried your demo page this morning and it is the same experience as my demo.

![915BBAF8-BE2C-45DE-A0A7-D6608DCAB752](https://github.com/user-attachments/assets/33317cab-131c-4511-beae-3e0741447b0a)

**Comment by philfung** [comment] 2024-08-19 02:08
fixed in https://github.com/philfung/add-to-homescreen/commit/239f2a8ca09edaf19b66df627ca5b774811af85f and created a new release https://github.com/philfung/add-to-homescreen/releases/tag/1.9

**Closed by philfung** 2024-08-19 02:08 UTC
