### ISSUE TITLE
"Add to Home Screen" doesn't change with locale

### ISSUE THREAD

**Issue by claudiobosticco** [philfung/add-to-homescreen#45] opened 2024-10-23 07:33 UTC
Hello, on Android it seems that it's always using the "Add to Home Screen" value in English locale (or maybe the key?) when using locales different from en, for example with locale it:

![2024-10-23 09 32 11](https://github.com/user-attachments/assets/79077280-40b8-490d-8e98-8d25453e582a)

**Comment by wss2** [comment] 2024-10-23 13:08
Hi @claudiobosticco I can't set locale as IT 
where am I wrong?
`window.AddToHomeScreenInstance.show('it');`

**Comment by claudiobosticco** [comment] 2024-10-23 13:14
I must specify that I'm loading the it locale from https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.1/dist/add-to-homescreen_it.min.js, and in this file I see a mix of English and Italian messages 🤔

**Comment by claudiobosticco** [comment] 2024-10-23 13:23
Sorry, I posted without noticing you reply. I don't know, that exact line of code is working for me 🤔
And now I've tried 'fr' and I see the same problem:
![image](https://github.com/user-attachments/assets/0efc2bc7-a511-465b-8af1-9ac041fff7ea)

**Comment by claudiobosticco** [comment] 2024-10-23 13:28
> I must specify that I'm loading the it locale from https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.1/dist/add-to-homescreen_it.min.js, and in this file I see a mix of English and Italian messages 🤔

but actually I don't see other messages in the wrong locale, just "Add to Home Screen"

**Comment by wss2** [comment] 2024-10-23 13:52
Done, I found the work around for both.
In my case it was simple, I loaded the js without translation.
In your case the translation is missing so I can tell you what I did.
I downloaded the .min and copied to [https://unminify.com/](https://unminify.com/) to make it readable. Then I searched for and replaced "Add to home screen" with "Aggiungi alla Home" and then I used the file locally.
I hope I have been helpful to you.

**Comment by wss2** [comment] 2024-10-23 13:52
> > I must specify that I'm loading the it locale from https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.1/dist/add-to-homescreen_it.min.js, and in this file I see a mix of English and Italian messages 🤔
> 
> but actually I don't see other messages in the wrong locale, just "Add to Home Screen"

Done, I found the work around for both.
In my case it was simple, I loaded the js without translation.
In your case the translation is missing so I can tell you what I did.
I downloaded the .min and copied to [https://unminify.com/](https://unminify.com/) to make it readable. Then I searched for and replaced "Add to home screen" with "Aggiungi alla Home" and then I used the file locally.
I hope I have been helpful to you.

**Comment by claudiobosticco** [comment] 2024-10-23 14:09
Okay, but no CDN then. Is it not possible to fix the hosted version?

**Comment by philfung** [comment] 2024-10-24 21:31
@claudiobosticco thanks for highlighting this issue.  It actually was caused by a bug in our build process where only the first string was translated and not every (minor fyi @shaneosullivan).  Now fixed and made a new [release](https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.3).

**Closed by philfung** 2024-10-24 21:31 UTC
